### PR TITLE
Support StackExchange.Redis version 2.2.79

### PR DESCRIPTION
**Pull request by idankri**
Support StackExchange.Redis version 2.2.79

### CODE REVIEW

**Comment by maca88** [comment]
Is there any reason why not upgrade to the latest version `2.6.66`?

**Comment by maca88** [comment]
I made a PR (#4) for updating it to version `2.6.66`. Unfortunately it seems that `StackExchange.Redis` is introducing binary changes also with minor versions, therefore in my PR the version is fixed to `2.6.66` and also aligned the version of this library to be the same. In case you can upgrade to `2.6.66`, I will close this PR and merge the other one.

**Comment by idankri** [comment]
Hey, thank you! Amazing that you aligned to the latest version, and totally should be done :) If it's not much painful, would be awesome to merge this one and then merge your version (which I would assume have the same changes and another alignments), exactly for the reason you mentioned (one of the patches from another dependency I have broke my repo)
If it is painful then close this one and I will align.
Thanks again!

**Comment by maca88** [comment]
> If it's not much painful, would be awesome to merge this one and then merge your version (which I would assume have the same changes and another alignments)

In the other PR these methods are now generated by using Roslyn as there were a lot new methods and it was painful to add them all manually. I don't see a point merging this PR as this code is moved to a different class and would produce merge conflicts, so I will close it. Still thank you for contributing to the project :)

**Comment by maca88** [comment]
The new version `2.6.66` was published on NuGet.

**Pull request closed without merging**
